Repository Xceptance/xlt-documentation, pull requests merged in 2020-11, with the labels that each got.

#10 Added some missing knowledge about merge rules
  content/en/load-testing/Advanced/010-merge-rules.md
Labels: documentation, enhancement

#11 Review of 050-workflow.md
  content/en/load-testing/Manual/050-workflow.md
Labels: documentation

#13 Js.dev new
  content/en/about-xlt/_index.md
  content/en/license.md
  content/en/load-testing/Advanced/200-maven-builds.md
  content/en/load-testing/Manual/040-installation.md
  content/en/load-testing/Quick Start/10-installation.md
Labels: documentation

#14 GitHub action
  .github/workflows/main.yml
  .github/workflows/scripts/mirrorftp
  BUILDME.md
  package-lock.json
  package.json
Labels: enhancement

#15 Small changes everywhere
  content/en/_index.html
  content/en/about-xlt/000-demo/index.md
  content/en/about-xlt/05-target-audience.md
  content/en/about-xlt/10-history.md
  content/en/about-xlt/20-feature-overview.md
  content/en/about-xlt/80-license.md
  content/en/about-xlt/990-disclaimer.md
  content/en/about-xlt/_index.md
  content/en/load-testing/11-glossary.md
  content/en/load-testing/Manual/010-basics.md
  content/en/load-testing/Manual/030-concepts.md
  content/en/load-testing/Manual/320-test-evaluation.md
  content/en/load-testing/Manual/440-result-browser.md
  content/en/load-testing/Manual/600-client-performance.md
  content/en/load-testing/Manual/700-limitations.md
  content/en/load-testing/Quick Start/_index.md
  content/en/load-testing/_index.md
  themes/xltdoc/assets/scss/_styles_project.scss
  themes/xltdoc/layouts/shortcodes/TODO.html
Labels: documentation
