Repository Xceptance/xlt-documentation, pull requests merged in 2021-05, with the labels that each got.

#52 RSS and Sitemap
  config.toml
  themes/xltdoc/layouts/list.rss.xml
  themes/xltdoc/layouts/sitemap.xml
Labels: bug, enhancement

#53 Release notes for XLT 5.4.1
  content/en/release-notes/5.4.x.md
Labels: documentation

#55 license
  LICENSE
  config.toml
  themes/xltdoc/assets/scss/_styles_project.scss
  themes/xltdoc/i18n/en.toml
  themes/xltdoc/layouts/partials/footer.html
Labels: documentation

#58 Unblock Robots by default
  themes/xltdoc/layouts/partials/head.html
Labels: bug
